server:
  port: 1026

spring:
  profiles:
    #    active: datasource
    #    配置生产环境为 dev
    active: datasource,dev
  #redis相关配置
  redis:
    database: 0
    # 配置redis的主机地址，需要修改成自己的
    host: 82.157.231.20
    password: redis257248
    port: 6379
    timeout: 8000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 50
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 5
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 100
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 5000

expire:
  token: 259200 # 三天 （秒）
  verification: 300 # 两分钟 （秒）

paths:
  nocheck: /users/login, /users/register, /mail, /swagger, /errorpage, /redis, /favicon.ico

poemCount: 50

